name: test npm workflow

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - '**/package.json'
      - '**/package-lock.json'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout using tag v2
        uses: actions/checkout@v2

      - name: Checkout using sha v3
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'  # adjust as needed

      - name: Print npm version
        run: npm --version

      - name: Install dependencies
        run: npm ci

      - name: Audit dependencies
        run: npm audit --audit-level=moderate || true

      - name: Run tests (if any)
        run: npm test || echo "No tests defined"

      - name: Build project (if applicable)
        run: npm run build || echo "No build step defined"
