name: test npm workflow

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - '**/package.json'
      - '**/package-lock.json'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout using tag v2
        uses: actions/checkout@v4

      - name: Checkout using sha v3
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'  # adjust as needed

      - name: Print npm version
        run: npm --version
